name: money_assistant_2608
description: A new Flutter project.
publish_to: 'none'
version: 1.0.8

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_sign_in: ^6.1.5
  firebase_auth: ^4.9.1
  firebase_core: ^2.15.1
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_screenutil: ^5.9.0
  flutter_login: ^5.0.0
  flutter_screen_lock: ^5.0.7
  flutter_app_lock: ^4.0.0
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^24.2.8
  day_night_time_picker: ^1.2.0+2
  flutter_material_pickers: ^3.3.0
  sliding_up_panel: ^2.0.0+1
  keyboard_actions: ^4.2.0
  fluttertoast: ^8.2.2
  flutter_swipe_action_cell: ^3.1.3
  share_plus: ^7.1.0
  in_app_review: ^2.0.6
  rate_my_app: ^2.0.0

  # icons
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.6.0
  flutter_boxicons: ^3.0.0
  icofont_flutter: ^1.4.0
  cupertino_icons: ^1.0.5

dependency_overrides:
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#ffffff"
  image: images/splash_screen.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/project/localization/lang/
    - images/
