name: money_assistant_2608
description: A new Flutter project.
publish_to: 'none'
version: 1.0.8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_sign_in: ^5.2.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_login: ^2.2.1
  flutter_screen_lock: ^4.0.4+2
  flutter_app_lock: ^2.0.0
  google_fonts: ^2.1.0
  table_calendar: ^3.0.2
  syncfusion_flutter_charts: ^20.4.54
  day_night_time_picker: ^1.0.3+1
  flutter_material_pickers: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  keyboard_actions: ^3.4.4
  fluttertoast: ^8.2.1
  flutter_swipe_action_cell: ^3.1.0
  share_plus: ^2.1.4
  in_app_review: ^2.0.3
  rate_my_app: ^1.1.1

  # icons
  material_design_icons_flutter: ^4.0.5955
  font_awesome_flutter: ^9.1.0
  outline_material_icons: ^0.1.1
  flutter_boxicons: ^3.0.0
  icofont_flutter: ^1.4.0
  cupertino_icons: ^1.0.3

dependency_overrides:
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3

flutter_native_splash:
  color: "#ffffff"
  image: images/splash_screen.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/project/localization/lang/
    - images/
