  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.2

      - run: flutter pub get

      - name: 🔥 ERASE bad Java path & upgrade AGP
        run: |
          # 1. Remove any rogue java-home
          sed -i '/org.gradle.java.home.*/d' android/gradle.properties 2>/dev/null || true
          # 2. Force AGP 7.4.2 (Flutter 3.24 compatible)
          perl -0777 -pe "s|classpath 'com.android.tools.build:gradle:[^']*'|classpath 'com.android.tools.build:gradle:7.4.2'|g" android/build.gradle
          # 3. Accept the new template
          flutter build apk --release --android-skip-build-dependency-validation

      - uses: actions/upload-artifact@v4
        with:
          name: money-tracker-release
          path: build/app/outputs/flutter-apk/app-release.apk
